name: Publish releases

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Update package.json
        uses: adobe/update-prerelease-npm-version@v1.2.0

      - name: Publish
        run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
