name: Publish on push

on:
  push:
    branches:
      - main

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to publish packages with provenance
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Update package.json
        uses: adobe/update-prerelease-npm-version@4dea8f295023f5b18126afd79bae1057a5b92d6e # v1.2.0

      - name: Publish
        run: pnpm publish --provenance --no-git-checks --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deprecate old versions
        run: pnpm npm-deprecate --name "*-pre.*" --package disfluent
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
